Support friendly urls
EasyDynamics/oscal-rest-service pull request #108
Opened 2022-07-01 17:31 UTC by tuckerzp

This adds the ability for the `ViwerAppController` to correctly
map urls when provided a uuid.

2022-07-01 17:36 UTC, kylelaker requested changes

2022-07-01 17:36 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/ViewerAppController.java
> +  @GetMapping({ "system-security-plan/**", "catalog/**", "component-definition/**", "profile/**" })
Please make the Javadoc actually meaningful

2022-07-01 17:36 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/ViewerAppController.java
> +    }
This is the kind of complexity that isn't immediately clear to a future reader/maintainer of this code and that I don't think we can more clearly express via refactoring. Can you write a comment (it'll probably need to be a couple sentences or more) to explain why this is the way that it is?

2022-07-01 20:42 UTC, Bronstrom requested changes
Looking good! I have no issues with code, and a couple suggestions on documentation.

2022-07-01 20:42 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/ViewerAppController.java
> +    // UUID.fromString throws an exception when attempting to parse an invalud
```suggestion
    // UUID.fromString throws an exception when attempting to parse an invalid
```
"Invalid" is misspelled

2022-07-01 20:42 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/ViewerAppController.java
> +    // wildcard, we return /index.html/{wildCard} and let that get mapped if
```suggestion
    // wildcard, we return "/index.html/{wildCard}" and let that get mapped if
```

To separate what you're referencing in code from your documentation, it might be best to put this in quotes.

2022-07-01 20:42 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/ViewerAppController.java
> +    // necessary to be done.
```suggestion

```

This sentence doesn't appear to add anything to the documentation.

2022-07-01 20:42 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/ViewerAppController.java
> +    // UUID. So upon successfully parsing a uuid from the wildcard, /index.html
```suggestion
    // UUID. So upon successfully parsing a uuid from the wildcard, "/index.html"
```

Would suggest putting document referenced in quotes.

2022-07-05 17:04 UTC, Bronstrom approved these changes

2022-07-05 17:04 UTC, kylelaker approved these changes

2022-07-05 17:05 UTC, merged