Feature/fix component UUID save
EasyDynamics/oscal-rest-service pull request #125
Opened 2022-08-02 16:50 UTC by Bronstrom

When running OSCAL Editor and attempting to save changes to numbered control statements occurring with a decimal (eg. AC-1.2) when in an SSP model example, the results wouldn't be saved. This is a result of the `by-component`'s `component-uuid` is not being set. In order to fix this change, the endpoints for a `statement` and `by-component` needed to be implemented for an SSP in the REST service.

To handle saving the `component-uuid`, `statements` and `by-components` were implemented in a similar fashion to `implemented requirements` in the ssp. This involved setting up marshallers for both extending `BaseOscalObjectMarshallerLiboscalIml` and creating beans in the apps `ServiceConfig`. Several helper methods assist with updating/adding `statements` or `by-components` which are saved in lists underneath their respective hierarchically property.

Closes #100

2022-08-02 16:55 UTC, Bronstrom commented
With there being a lot of code being implemented here I thought I might pick out a few things to make it a little easier to review. Below is an example of how I would grab an `ImplementedRequirement` from a `ControlImplementation` in an SSP. I use an enhanced for loop to run through the list of `ImplementedRequirements` to grab the `implementedRequirement` with the matching `uuid`. I don't like how I create a `potetialImpReq` variable and then assign the value later to `existingImplReq` later. I feel like this is wasteful I do a similar thing with grabbing `statements` from `ImplementedRequirement`. I have tried to attempt this a single variable, although I later receive the error that this variable must be "defined in an enclosing scope must be final or effectively final."
```
List<ImplementedRequirement> implReqs = existingSsp.getControlImplementation().getImplementedRequirements();
ImplementedRequirement potentialImplReq = null;
for (ImplementedRequirement implReq : implReqs) {
    if (implementedRequirementId.equals(implReq.getUuid().toString())) {
        potentialImplReq = implReq;
    }
}
ImplementedRequirement existingImplReq = potentialImplReq;
```

Secondly, when I have acquired a `Statement` or `ByComponent` I end up testing the levels of hierarchy above and it get quite messy. I was curious if this seems necessary as this is more something that would be checked beforehand.

Please let me know if you have any suggestions in either of these places.

Also, I plan on refactoring this code a bit because there is a bit of duplication, and it doesn't seem like there needs to be a method for each individual properties of an SSP.

2022-08-02 17:07 UTC, kylelaker requested changes

2022-08-02 17:07 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    if (existingStmt == null) {
Refactor this to actually use the `Optional` instead of just falling back to using `null`.

2022-08-02 17:07 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    }
Please use streams and filters as you've done elsewhere

2022-08-02 17:07 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    }
Stream, filter, findAny

2022-08-02 17:07 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +      addComponentToList(existingStmt, incomingByComp);
This looks really familiar to other code I reviewed above...

2022-08-02 17:07 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    Statement existingStmt = potentialStmt;
Why do we alias this and then never use the original value?


```suggestion
    Optional<Statement> existingStmt = existingImplReq.getStatements()
      .stream()
      .filter(stmt -> statementId.equals(stmt.getUuid().toString())
      .findAny();
```

2022-08-02 17:54 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    Statement existingStmt = potentialStmt;
Originally I wasn't aliasing and just had `exisitingStmt`, but was getting a "defined in an enclosing scope must be final or effectively final" error later. Aliasing avoided this error.  `streams()` and `filters()` are a much better approach.

2022-08-02 18:14 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    Statement existingStmt = potentialStmt;
By using `Optional`, methods like `getUUid()` and `getStatement()` cannot be used with this type. Specifically I get the error: "The method getUuid() is undefined for the type Optional<ImplementedRequirement>"

2022-08-02 18:15 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    Statement existingStmt = potentialStmt;
How's this instead?

```suggestion
   ImplementedRequirement existingImplReq =
        existingSsp.getControlImplementation().getImplementedRequirements().stream()
        .filter(implReq -> implementedRequirementId.equals(implReq.getUuid().toString()))
        .findAny().orElse(null);
```

2022-08-02 18:51 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    } else {
Would it be better to use Optional here too, rather than `null` and check to see if the value is empty when adding to the list?

2022-08-02 18:54 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    } else {
If you get an `Optional` as part of your calls sorta by default, then yeah. Try to use that instead of just converting it to `null`.

2022-08-03 16:07 UTC, zclarkEDC commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    if (incomingUuid != null && !id.equals(incomingUuid.toString())) {
Should we also check `!incomingUuid.isEmpty()` as part of this `if` statement?

2022-08-03 16:13 UTC, tuckerzp commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    if (incomingUuid != null && !id.equals(incomingUuid.toString())) {
I think it it was `empty` it would be `null`. I may be wrong though. Looking at [`UUID`](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/UUID.html), it does not seem to have an `isEmpty()` method.

2022-08-03 16:24 UTC, Bronstrom commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    if (incomingUuid != null && !id.equals(incomingUuid.toString())) {
It doesn't look like `UUID` has an `isEmpty()` method. I think it would be okay to handle null `here`. Kyle had mentioned handling `filter().findAny()` above as `Optional` because these return `empty` by default.

2022-08-04 18:53 UTC, closed without merging