chore(deps): Bump spring-boot-starter to 3.0.4
EasyDynamics/oscal-rest-service pull request #178
Opened 2023-02-28 20:31 UTC by Bronstrom

This handles the bump for
`spring-boot-starter-parent` from 3.0.2 to 3.0.4.
It appears we do not need to define a version
for `spring-boot-starter-data-jpa`, unless we
desired a version differing from the starter
parent. Maven by default will download
jar files based on the version defined for the
starter parent tag, which will be used as the
version towards dependencies with the
`org.springframework.boot` `groupId`. Occurrences of
`spring-boot-starter-data-jpa.version` have been
removed to avoid additional spring boot starter
PRs.

2023-03-03 19:49 UTC, kylelaker approved these changes

2023-03-03 19:50 UTC, kylelaker commented
> It appears we do not need to define a version
> for `spring-boot-starter-data-jpa`, unless we
> desired a version differing from the starter
> parent

Can you provide a source for this?

2023-03-03 20:04 UTC, Bronstrom commented
Here are two sources I used explaining this: [baeldung.com/spring-boot-starter-parent#managing-dependencies](https://www.baeldung.com/spring-boot-starter-parent#managing-dependencies:~:text=We%20also%20don%27t%20need%20to%20define%20versions%20of%20the%20dependencies%3B%20Maven%20will%20download%20jar%20files%20based%20on%20the%20version%20defined%20for%20the%20starter%20parent%20in%20the%20parent%20tag.) & [geeksforgeeks.org/spring-boot-dependency-management](https://www.geeksforgeeks.org/spring-boot-dependency-management/#:~:text=Also%2C%20you%20don%E2%80%99t%20need%20to%20mention%20the%20version%20of%20the%20dependencies%2C%20as%20Spring%2DBoot%20configures%20them%20automatically.%20Though%20you%20can%20mention%20the%20version%20or%20override%20as%20well.)

2023-03-06 13:11 UTC, tuckerzp approved these changes

2023-03-06 13:30 UTC, tuckerzp commented
@Bronstrom can we bump this to 3.0.4 to close #180 & #181

2023-03-06 14:18 UTC, Bronstrom commented
> @Bronstrom can we bump this to 3.0.4 to close https://github.com/EasyDynamics/oscal-rest-service/pull/180 & https://github.com/EasyDynamics/oscal-rest-service/pull/181

Just updated.

2023-03-10 13:08 UTC, tuckerzp commented
@Bronstrom can you fix conflicts so we can merge this in?

2023-03-10 17:32 UTC, kylelaker requested changes

2023-03-10 17:32 UTC, kylelaker commented on .github/workflows/gh-packages.yml
> +        uses: actions/delete-package-versions@v4
This is an incorrect change. Please see #171

2023-03-10 17:32 UTC, kylelaker commented on oscal-data-repository-commons/pom.xml
> +		<liboscal-java.version>1.0.4.3</liboscal-java.version>
This downgrade is incorrect too. Please review the merge commit and attempt to resolve the conflicts again.

2023-03-10 17:34 UTC, Bronstrom commented on .github/workflows/gh-packages.yml
> +        uses: actions/delete-package-versions@v4
I think my develop branch got messed up. I'll fix this

2023-03-14 19:53 UTC, kylelaker approved these changes

2023-03-14 19:53 UTC, merged