Ability to add and update SSP Impl Req
EasyDynamics/oscal-rest-service pull request #94
Opened 2022-05-12 17:53 UTC by rgauss

- Created an `OscalSspImplReqMarshallerImpl`
- Updated `IterableAssemblyClassBinding` to define a list of
`secondaryRootObjects` that will 'trick' the deserializer to allow as
root objects
- Updated `BaseOscalObjectMarshallerLiboscalImpl` to be able to create
deserializer with `IterableAssemblyClassBinding`
- Updated `SspController` and tests

Closes #57
Closes #58

2022-05-13 01:55 UTC, kylelaker reviewed
Okay so _love_ this. I started to take a look at doing this and got a little put off (overwhelmed) by the fact this was the first time we're really handling any sort of non-universal "inner" elements (because like we play with UUID and Metadata but everything root has one of those). So not only is this cool because I want _this_ feature but I think this is cool because it's a really good starting point for all the features to come which is really exciting.

Nothing here is concerning enough to me to block merging but I do want to ask a few questions to make sure I understand what's going on before I fully approve (and of course, while I was making comments anyway, I made fun of Java once or twice).

2022-05-13 01:55 UTC, kylelaker commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +        new QName("implemented-requirement"));
So eventually, we'd also put something like:

```java
secondaryRootObjects.put(Control.class, new QName("control"));
secondaryRootObjects.put(Component.class, new QName("component"));
```

?

2022-05-13 01:55 UTC, kylelaker commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +
Because we only ever use the interface here, we never write to it after building, and we're Java 11+, we could potentially just use [`Map.ofEntries`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#ofEntries(java.util.Map.Entry...)). But if there's a specific reason to use `HashedMap`, this may not work for us.

I am also pretty biased against initializers.

```suggestion
  private static final Map<Class<?>, QName> secondaryRootObjects = Map.ofEntries(
    Map.entry(ImplementedRequirement.class, new QName("implemented-requirement"),
  );
```

2022-05-13 01:55 UTC, kylelaker commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +  }
```suggestion
    return secondaryRootObjects.getOrDefault(getBoundClass(), super.getRootXmlQName());
  }
```

2022-05-13 01:55 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +      OscalObjectMarshaller<ImplementedRequirement> oscalSspImplReqtMarshaller
To make sure I understand, we're eventually going to need a Marshaller for Components as well?

2022-05-13 01:55 UTC, kylelaker commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +import org.apache.commons.collections4.map.HashedMap;
Just curious, why is this preferable to `java.util.HashMap`?

2022-05-13 01:55 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +        && existingSsp.getControlImplementation().getImplementedRequirements() != null) {
Really missing the `?.` operator right now

2022-05-13 01:55 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +          .findAny()
Do we check for duplicate IDs anywhere? Here we will pick one (potentially at "random") and mutate that one if the `filter` has >1 elements. I suppose envisioning that a user PUT/POST(ed) a "bad" document initially and now we're going to update, should we 400/409/500, update one of them, or update all of them?

Here, as I read it, we arbitrarily update one. And as a user, I'd probably expect none or all to be modified.

I also don't know that we need to answer this today in this ticket; but I do think we may want to at least create a new ticket for it if we don't answer.

2022-05-13 01:55 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/OscalControllerExceptionAdvice.java
> +  @ResponseStatus(HttpStatus.CONFLICT)
Technically, I think this needs a spec update

2022-05-13 11:45 UTC, rgauss commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +        new QName("implemented-requirement"));
That's correct.

2022-05-13 11:48 UTC, rgauss commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +      OscalObjectMarshaller<ImplementedRequirement> oscalSspImplReqtMarshaller
Potentially.  We may end up exposing a generic implementation that can take a class as an argument.

2022-05-13 11:49 UTC, rgauss commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +import org.apache.commons.collections4.map.HashedMap;
Errant auto-complete.

2022-05-13 11:57 UTC, rgauss commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +          .findAny()
The code definitely assumes the existing data has been validated (unique IDs), and I believe the marshaling (via liboscal-java) called on save is configured to perform some validation though I don't see a uniqueness constraint for Implemented Requirements UUID in particular on quick look through liboscal-java's generated models.

Another ticket for a deeper investigation of validation in general would be great.

2022-05-13 12:03 UTC, rgauss commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/OscalControllerExceptionAdvice.java
> +  @ResponseStatus(HttpStatus.CONFLICT)
Yes, EasyDynamics/oscal-rest#50.

2022-05-13 12:04 UTC, rgauss commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +
Addressed.

2022-05-13 12:04 UTC, rgauss commented on oscal-data-repository-commons/src/main/java/com/easydynamics/oscal/data/marshalling/IterableAssemblyClassBinding.java
> +  }
Addressed.

2022-05-13 13:02 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +          .findAny()
I'll write that ticket later today!

2022-05-13 21:04 UTC, kylelaker approved these changes

2022-05-14 03:48 UTC, kylelaker requested changes
See https://github.com/EasyDynamics/oscal-rest-service/pull/95 for issues around spec compliance. It was a little too cumbersome to add as suggestions directly in this PR.

2022-05-14 17:32 UTC, hreineck requested changes
Awesome! Works great in my local Docker deployment.
Only a couple notes.

2022-05-14 17:32 UTC, hreineck commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +      throw new OscalObjectConflictException("Implented Requirement already exists");
```suggestion
      throw new OscalObjectConflictException("Implemented Requirement already exists");
```

2022-05-14 17:32 UTC, hreineck commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    return updateImplementedRequirement(id, implementedRequirementId, json, false);
Should the PUT only update existing impl reqs? Or should it also add a new one? Not sure if we ever specified.

2022-05-14 17:32 UTC, hreineck commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +  private final OscalObjectMarshaller<ImplementedRequirement> oscalSspImplReqtMarshaller;
```suggestion
  private final OscalObjectMarshaller<ImplementedRequirement> oscalSspImplReqMarshaller;
```

Maybe change this to match the naming convention of "Impl Req" used elsewhere

2022-05-14 17:32 UTC, hreineck commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +      + "implemented-requirements/{implementedRequirementId}",
Per the API spec, the POST request does not include the `implementedRequirementID` as a parameter.

Kind of annoying because the ID validation cannot happen in the marshaller - the functionality probably needs to be separated between the POST and PUT.

2022-05-14 17:34 UTC, hreineck commented
Per my comment about the POST endpoint parameters, see the commits I just pushed for a potential way to separate out the POST and PUT endpoints

2022-05-14 20:12 UTC, kylelaker commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    return updateImplementedRequirement(id, implementedRequirementId, json, false);
I feel like we talked about this a little bit at one point when we added PUT/PATCH somewhere else (but I can't remember at the moment). I don't remember a strong decision being reached one way or another.

_Theoretically_ these two _should_ be compatible:

```
POST /system-security-plans/bb44ca2a-385b-4820-a3ba-b541b9569969/control-implementations/implemented-requirements

{
  "uuid: "762b1d87-1515-4253-a2ad-0e58dcc645a1"
  ...
}
```

```
PUT /system-security-plans/bb44ca2a-385b-4820-a3ba-b541b9569969/control-implementations/implemented-requirements/762b1d87-1515-4253-a2ad-0e58dcc645a1

{
  "uuid": "762b1d87-1515-4253-a2ad-0e58dcc645a1",
  ...
}
```

I think the difference here would be a little more clear if we _didnt_ require the `uuid` in the POST and PUT body (which I think I'd actually almost prefer for the spec). So then if a client had a preference for a UUID for a new resource for some reason (if you've already created a resource that references it or something or you're maybe doing some kind of migration), then you specify it (again, with POST and PUT being equivalent).

So skipping a few implementation details and abstracting a bit, I feel like as a user, I'd want the API/service to work a bit like this

```mermaid
graph LR
  Init([Make a request]) --> Pref{Preference on UUID}
  Pref -->|Yes| PUT
  Pref -->|No| POST
```

And

```mermaid
graph LR
  POST([POST]) --> UUID{Is UUID specified in body}
  UUID -->|Yes| Error([Error])
  UUID -->|No| Z[Create new Impl Req<br/>and generate UUID]
```

```mermaid
graph LR
  PUT([PUT]) --> UUID{Is UUID specified in body}
  UUID -->|No| Exist
  UUID -->|Yes| UUIDMatch
  UUIDMatch{Does the body UUID<br/>match path UUID}
  UUIDMatch -->|No| Error([Error])
  UUIDMatch -->|Yes| Exist
  Exist{Does a resource with the<br/>UUID already exist}
  Exist -->|Yes| Update[Update matching resource]
  Exist -->|No| Create[Create new<br/>Impl Req with given UUID]
```

2022-05-17 10:45 UTC, rgauss commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +      throw new OscalObjectConflictException("Implented Requirement already exists");
Addressed

2022-05-17 10:47 UTC, rgauss commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +    return updateImplementedRequirement(id, implementedRequirementId, json, false);
@kylelaker, I'd agree with this.

Can you please create an issue to add a generic version of this (not specific to impl req) in the `oscal-rest` repo as 'implementation guidance' documentation?

2022-05-17 10:47 UTC, rgauss commented on oscal-rest-service-app/src/main/java/com/easydynamics/oscalrestservice/api/SspController.java
> +  private final OscalObjectMarshaller<ImplementedRequirement> oscalSspImplReqtMarshaller;
Addressed

2022-05-18 01:28 UTC, kylelaker approved these changes
Thanks for your changes! This looks good as far as I can tell. We still need to see why the Viewer doesn't update after a PUT but right now I'm not sure anyone else has reproduced that behavior and it also feels more likely to be a viewer bug.

2022-05-18 12:25 UTC, rgauss commented
> Thanks for your changes! This looks good as far as I can tell. We still need to see why the Viewer doesn't update after a PUT but right now I'm not sure anyone else has reproduced that behavior and it also feels more likely to be a viewer bug.

@kylelaker, see EasyDynamics/oscal-react-library#396

2022-05-19 13:20 UTC, hreineck approved these changes

2022-05-20 13:09 UTC, merged